#!/bin/bash
set -eo pipefail

host="mssql-edge"
port="1433"
user="${MSSQL_USER:-SA}"
db="${MSSQL_DB:-master}"
sqlcmd="/opt/sqlcmd/bin/sqlcmd}"

args=(
	-S "tcp:$host,$port"
	-U "$user"
	-d "$db"
	-b
)

export SQLCMDPASSWORD="${MSSQL_SA_PASSWORD:-}"
if select="$(${sqlcmd} ${args[@]} -Q "SELECT 1" 2>/dev/null)" && [[ $? == 0 && "$select" != "" ]]; then
	exit 0
fi

exit 1
